config/routes.rb
Rails.application.routes.draw do

  resources :posts
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  resources :users
  root to: "users#index"

  get 'countries/fetch_cities'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country

  scope :country_id, -> (country_id) { where(country_id: country_id ) }
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities

  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  include AASM

  aasm :column => 'status_state', whiny_persistence: true do
    state :draft, initial: true
    state :scheduled, :on_moderation, :published, :canceled

    event :process_scheduled do
      transitions from: :draft, to: :scheduled, after: Proc.new { |*args| set_scheduled_at(*args) }
    end

    event :process_on_moderation do
      transitions from: [:draft, :scheduled], to: :on_moderation
    end

    event :mark_as_draft do
      transitions from: [:scheduled, :published, :canceled], to: :draft, after: :clear_excess_attributes
    end

    event :mark_as_published do
      transitions from: :on_moderation, to: :published, after: Proc.new { |*args| set_published_at(*args) }
    end

    event :mark_as_canceled do
      transitions from: :on_moderation, to: :canceled, after: Proc.new { |*args| set_cancellation_reason(*args) }
    end
  end

  def set_scheduled_at(current_datetime)
    self.scheduled_at = current_datetime
  end

  def set_published_at(moderator)
    self.moderator_id = moderator.id
    self.published_at = Time.now
    self.scheduled_at = nil
  end

  def set_cancellation_reason(moderator, reason)
    self.moderator_id = moderator.id
    self.cancellation_reason = reason
    self.scheduled_at = nil
  end

  def clear_excess_attributes
    self.moderator_id = nil
    self.published_at = nil
    self.scheduled_at = nil
    self.cancellation_reason = nil
  end

  belongs_to :user
  belongs_to :moderator, class_name: 'User', foreign_key: :moderator_id, required: false

  #scheduled_at validation
  validates :scheduled_at, presence: true, if: Proc.new { self.scheduled? }

  #scheduled_at & datetime validation gem 'validates_timeliness', '~> 6.0.0.beta2'
  validates_date :scheduled_at, on: :create, on_or_after: :today, if: Proc.new { self.scheduled? }

  #cancellation_reason validation
  validates :cancellation_reason, presence: true, if: Proc.new { self.canceled? }

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user


  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy

  belongs_to :city
  belongs_to :country

  validates :email, :username, presence: true
  validates :pin, length: { is: 11 }, presence: true, uniqueness: true




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def fetch_cities
    @cities = City.country_id(params[:country_id])
    render partial: 'cities', object: @cities, layout: false
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'simple'

  before_action :set_post, only: %i[ show edit update destroy ]

  before_action :set_users

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      result = PostInteractors::UpdatePost.call(
        additional_params: { action: params[:commit], moderator_id: post_params[:moderator_id] },
        post: @post,
        params: post_params
      )
      if result.success?
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      result = PostInteractors::UpdatePost.call(
        additional_params: { action: params[:commit], moderator_id: post_params[:moderator_id], cancellation_reason: post_params[:cancellation_reason] },
        post: @post,
        params: post_params
      )

      if result.success?
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  #
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:user_id, :scheduled_at, :moderator_id, :title, :body, :cancellation_reason)
  end

  def set_users
    @users = Profile.includes(:user)
    @current_user = User.find_by(is_admin: false)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'simple'

  before_action :set_default_country, only: %i[new create show edit update destroy]
  before_action :set_default_city, only: %i[edit]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @profile = @user.build_profile
  end

  def show
    @user = User.find(params[:id])
    @profile = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @profile = @user.build_profile(profile_params)

    if @user.save
      redirect_to users_url
    else
      @cities = City.country_id(@user.country_id)
      render :new
    end
  end


  def edit
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: params[:id])
  end

  def update
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: params[:id])

    if @user.update(user_params) && @profile.update(profile_params)
      redirect_to @user
    else
      redirect_to edit_user_path
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    respond_to do |format|
    format.html { redirect_to users_url, notice: "წარმატებით წაიშალა." }
    end
  end


  private

  def set_default_country
    @countries = Country.all
    @cities = []
    end

  def set_default_city
    @user = User.find(params[:id])
    @cities = City.where(country_id: @user.country_id)
  end



  def user_params
    params.require(:user).permit(:email, :username, :pin, :terms_of_use, :country_id, :city_id)
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :phone_number, :birth_date, :about_me)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_styled_badge(status)
    badge_class =
      case status
      when 'draft'
        'badge bg-secondary'

      when 'scheduled'
        'badge bg-info text-dark'

      when 'on_moderation'
        'badge bg-warning text-dark'

      when 'published'
        'badge bg-success'

      when 'canceled'
        'badge bg-danger'

      else
        'badge bg-primary'

      end
    content_tag(:span, status, class: badge_class)

  end

  def post_styled_date(current_date)
    current_date&.strftime("%Y-%m-%d %H:%M")
  end

end

app/views/countries/_cities.html.erb
<%= options_for_select(@cities.map { |c| [c.name, c.id] }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedicalApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container container-sm">
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, @users, :user_id, :full_name %>
  </div>

  <% if @current_user&.is_admin? %>

    <div class="field">
      <%= form.label :moderator_id  %>
      <%= form.collection_select :moderator_id, @users, :user_id, :full_name %>
    </div>

  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <% if @current_user&.is_admin? %>

    <div class="field">
      <%= form.label :cancellation_reason %>
      <%= form.text_field :cancellation_reason %>
    </div>

  <% else %>

  <div class="field">
    <%= form.label :scheduled_at %>
    <%= form.datetime_field :scheduled_at %>
  </div>

  <% end %>

  <div class="actions">
    <% if @current_user&.is_admin? %>

      <%= form.button 'Publish', name: "commit", value: 'published', class: 'btn btn-success' %>
      <%= form.button 'Cancel', name: "commit", value: 'canceled', class: 'btn btn-danger' %>

    <% else %>

      <%= form.submit 'Update Post', class: 'btn btn-primary' %>
      <%= form.button 'Moderation', name: "commit", value: 'moderation', class: 'btn btn-warning' %>
      <%= form.button  'Schedule Moderation', name: "commit", value: 'scheduled', class: 'btn btn-warning' %>

    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success' %>
  </div>
</div>

<br>
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col"></div>

      <h1>Posts</h1>

      <table class="table">
        <thead class="table-dark">
        <tr>
          <th>User</th>
          <th>Moderator</th>
          <th>Title</th>
          <th>Status</th>
          <th>Scheduled_At</th>
          <th>Published_At</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td class="align-middle"><%= post.user.username %></td>
            <td class="align-middle"><%= post.moderator&.username %></td>
            <td class="align-middle"><%= link_to post.title, post %></td>
            <td class="align-middle"><%= post_styled_badge(post.status_state)  %></td>
            <td class="align-middle"><%= post_styled_date(post.scheduled_at)  %></td>
            <td class="align-middle"><%= post_styled_date(post.published_at)  %></td>
            <td class="align-middle"><%= link_to 'Edit', edit_post_path(post) %></td>
            <td class="align-middle"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Moderator:</strong>
  <%= @post.moderator_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form' } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h5 class="card-title">Main info</h5>

  <div class="card main-info">
    <div class="row">
      <div class="col-5">
        <%= f.label :email, class: 'form-label' %>
        <%= f.text_field :email, class: 'form-control form-control-sm' %>
      </div>
    </div>

    <div class="row">
      <div class="col-5">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-control form-control-sm' %>
      </div>
    </div>


    <div class="row">
      <div class="col-5">
        <%= f.label :pin, class: 'form-label' %>
        <%= f.text_field :pin, class: 'form-control form-control-sm' %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">Terms of Use:</div>
    </div>

    <div class="row">
      <div class="col-1">
        <span class="form-check">
          <%= f.label :terms_of_use, 'Yes', class: 'form-label' %>
          <%= f.radio_button :terms_of_use, true, class: 'form-check-input' %>
        </span>
      </div>

      <div class="col-1">
        <span class="form-check">
          <%= f.label :terms_of_use, 'No', class: 'form-label' %>
          <%= f.radio_button :terms_of_use, false, class: 'form-check-input' %>
        </span>
      </div>
    </div>

    <div class="row" data-controller="countries">
      <div class="col-6">
        <%= f.collection_select :country_id, @countries, :id, :name,
                                { include_blank: 'Select Country' },
                                class: 'form-select',
                                data: {
                                  action: "change->countries#fetchCities",
                                  countries_target: "country"
                                }
        %>
      </div>

      <div class="col-6">
        <%= f.collection_select :city_id, @cities, :id, :name,
                                { include_blank: 'Select City' },
                                class: 'form-select',
                                data: {
                                  countries_target: "cities"
                                }
        %>
      </div>
    </div>

  </div>

  <h5 class="card-title">Profile</h5>
  <div class="card profile-block">
    <%= fields_for @profile do |ff| %>
      <div class="row">
        <div class="col-6">
          <%= ff.label :first_name, class: 'form-label' %>
          <%= ff.text_field :first_name, class: 'form-control form-control-sm' %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <%= ff.label :last_name, class: 'form-label' %>
          <%= ff.text_field :last_name, class: 'form-control form-control-sm' %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <%= ff.label :phone_number, class: 'form-label' %>
          <%= ff.text_field :phone_number, class: 'form-control form-control-sm' %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <%= ff.label :birth_date, class: 'form-label' %>
          <%= ff.date_field :birth_date, class: 'form-control form-control-sm' %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <%= ff.label :about_me, class: 'form-label' %>
          <%= ff.text_area :about_me, class: 'form-control form-control-sm' %>
        </div>
      </div>

    <% end %>
  </div>

  <div class="row float-end">
    <span class="action-buttons">
      <%= link_to 'Back', users_path, class: 'btn btn-lg btn-secondary' %>
      <%= f.button :submit, class: 'btn btn-lg btn-success' %>
    </span>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1> User Update</h1>

<div class="card user-block">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead class="table-dark">
  <tr>
    <th>ID</th>
    <th>Email</th>
    <th>Username</th>
    <th>Pin</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id   %></td>
      <td><%= user.email %></td>
      <td><%= user.username %></td>
      <td><%= user.pin %></td>
      <td><%= link_to 'Show', user, class: "btn btn-secondary" %></td>
      <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning" %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'დარწმუნებული ხარ ?' }, class: "btn btn-danger"%></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-success" %>

app/views/users/new.html.erb
<h1> Create User</h1>

<div class="card user-block">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<strong>მეილი:</strong>
<%= @user.email %>
<br>
<strong>სახელი:</strong>
<%= @user.username %>
<br>
<strong>პირადი ნომერი:</strong>
<%= @user.pin %>
<br>
<strong>ქვეყანა:</strong>
<%= @user.country.name %>
<br>
<strong>ქალაქი:</strong>
<%= @user.city.name %>
<br>
<strong>ეთანხმები წესებს ?:</strong>
<%= @user.terms_of_use %>
<br>
<%= link_to 'back', users_path, class: "btn btn-secondary" %>